version: '3.8'

#  docker-compose exec --user=root app bash
#  chown -R www-data:www-data /var/www

services:
    app:
        build:
            context: .
        container_name: diplom
        working_dir: /var/www
        volumes:
            - app-data:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage:/var/www/storage
            - ./app:/var/www/app
            - ./resources:/var/www/resources
            - ./routes:/var/www/routes
            - ./database:/var/www/database
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: diplom_webserver
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: diplom_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: diplom_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-data:
        driver: local
    dbdata:
        driver: local
    app-app:
        driver: local
    app-storage:
        driver: local
    app-resources:
        driver: local
    app-routes:
        driver: local
    app-database:
        driver: local
